<div class="aboutUS">
        <h1 class="page_header">About Us</h1>
        <p>
       <a class="highlighter i"> Excel India Publishers</a>, <a class="highlighter i"> Excel Seminar Solutions</a>, <a class="highlighter i"> Excel Publishing Services</a>, <a class="highlighter i"> Excel Printing Universe</a>,  together with <a class="highlighter i">Excel Technoassignment India Pvt. Ltd.</a> form <a class="highlighter i"> Group Excel India.</a></p>
        <p>
        Operations started with <b>Excel Publishing Services</b> which provides pre-press solutions to the publishing industry. Trained professionals offer you everything under one roof: data entry to the camera-ready copy. Individual projects on typesetting, layout designing, copy-editing, proofreading or book-indexing or cover designing Excel Publishing Services takes up any individual or integrated assignment pertaining to pre-press services.</p>
        <p>
        <b> Excel India Publishers</b> specialises in publication of conference proceedings. With other in-house units to take care of the finer details of pre-press activities, Excel India Publishers is equipped to handle publication of any type of Proceedings/ Book of Abstracts/ Souvenir relating to any conference/ seminar/ symposium and deliver them in the form you require: print or CD-ROM format. This also includes assigning an ISBN to the publication. Excel India Publishers is also associated with some institutions of repute to publish or process their journals, taking care of everything: right from acquiring the ISSN to the printed copy.</p>
        <p>
        <b> Excel Seminar Solutions</b> concentrates on jobs related to supply and printing of stationery and conference kit for international and national level seminars/ conferences/ symposia held by various academic institutions/ organisations. Right from brochures, posters, banners to the conference bags, writing pad, stationery and the memento for the delegates, Excel Seminar Solutions takes care of everything.</p>
        <p>
        <b> Excel Printing Universe</b> was born more as a necessity. When Excel Publishing Services, and Excel India Publishers begun churning out titles after titles and a huge volume of printing was required for the clients, addition of Excel Printing Universe was a logical culmination. Excel Printing Universe takes up printing on all kinds of media: paper, board, flex, vinyl, cloth, rexine or jute, apart from other types of surfaces. Offset, screen or digital, it provides a single-stop-solution and serves a long list of clients-most of them on regular basis.</p>
        <p>
        <b>Excel Technoassignment India Pvt. Ltd.</b> is the engineering arm of Group Excel India with interest in providing engineering services and solutions pertaining to Civil, Mechanical and IT. It also provides various construction equipments and machineries on lease across India.</p>
        </div>